### ISSUE TITLE
LOGIN USING GOOGLE ACCOUNT 

### ISSUE THREAD

**Issue by palsumit99** [DSC-JSS-NOIDA/Plasma-Donor-App#107]
I want to add a button where user can login using google account and also when the user is signed up for the plasma. There will be a message that this user is already signed in please login.

**Comment by palsumit99** [comment]
please assign this to me.

**Comment by vriddhi1203** [comment]
@dheerajkotwani  I would like to work on this issue. Please assign it to me. Thankyou
