### ISSUE TITLE
Login page UI improvement

### ISSUE THREAD

**Issue by sitamadex11** [DSC-JSS-NOIDA/Plasma-Donor-App#108]
I want to improve the login page UI.

**Comment by raghav-dalmia** [comment]
Go ahead. 👍

**Comment by sitamadex11** [comment]
thank you very much ,sir

**Comment by sitamadex11** [comment]
![Screenshot_20210405-235311_Plasma Donor App](https://user-images.githubusercontent.com/76570320/113613464-e788c000-966e-11eb-88f3-16109c33565a.jpg)
Sir I have made the signin page is it ok

**Comment by sitamadex11** [comment]
Sir there are 4 pages related to sign in and sign up.... May I work on them?

**Comment by dheerajkotwani** [comment]
> ?

yes you can

**Comment by sitamadex11** [comment]
ok thankyou
