### ISSUE TITLE
Implementing bottom navigation bar.

### ISSUE THREAD

**Issue by ayushman999** [DSC-JSS-NOIDA/Plasma-Donor-App#109]
**Is your feature request related to a problem? Please describe.**
It's the part of Figma design and I want to implement it.

**Describe the solution you'd like**
I'll be using the bottom navigation bar with and I'll try to keep the minsdk version low by using inbuilt features of android studio to create a bottom navigation bar.

**Describe alternatives you've considered**
It's a Figma design so I should implement it as it is.

**Additional context**
No

**Comment by yash10019coder** [comment]
I'm ready to implement this please assign me this

**Comment by ayushman999** [comment]
Ye project 2mahine se inactive hai. Maine khud ke task ke liye ye issue banaya tha.

**Comment by yash10019coder** [comment]
Ok  np
