### ISSUE TITLE
Hide Notification bar from Splash Screen

### ISSUE THREAD

**Issue by plazzy99** [DSC-JSS-NOIDA/Plasma-Donor-App#11]
**Is your feature request related to a problem? Please describe.**
It is a good practice of hiding the notification bar on the splash screen. One can notice this in almost all most downloaded app.

**Describe the solution you'd like**
Go write a few lines to hide the notification bar from the splash screen.

**Comment by rishipurwar1** [comment]
I would like to work on this issue

**Comment by plazzy99** [comment]
> I would like to work on this issue

Hi, @rishipurwar1 !!! We're glad that you want to contribute to this project but we would advise that start contributing from 1st October so as to make it count under Hacktoberfest 2020. See you then! Keep Learning :octocat:

**Comment by plazzy99** [comment]
@rishipurwar1 till the time you can fork the project and understand the current state of project.

**Comment by rishipurwar1** [comment]
Hello @plazzy99 , I am not able to contribute to this issue. I forgot to check the technology stack. So, please assign this issue to some else.
Sorry about that...

**Comment by plazzy99** [comment]
> Hello @plazzy99 , I am not able to contribute to this issue. I forgot to check the technology stack. So, please assign this issue to some else.
> Sorry about that...

okay, np

**Comment by abdulbasit75** [comment]
I would like to work on this issue, please assign this to me.

**Comment by dheerajkotwani** [comment]
@abdulbasit75 you can start working to it
