### ISSUE TITLE
Facebook Login and Google SignIn

### ISSUE THREAD

**Issue by sitamadex11** [DSC-JSS-NOIDA/Plasma-Donor-App#116]
In my recent UI update, I have added two buttons for google and facebook authentication. I want to Implement the functionality of Facebook and Google signin

**Comment by sitamadex11** [comment]
@dhruv-1001 sir whenever I had created the issue for UI changes then there was not any level tag (like level0, level1, etc) except the GSSOC21 tag. Therefore my PR is not counted and I didn't get any marks. May you please add a level tag on that issue?

**Comment by dhruv-1001** [comment]
I've added the level tag now.

**Comment by sitamadex11** [comment]
@dhruv-1001 thankyou verymuch sir

**Comment by AnubhavPabby** [comment]
@dhruv-1001 Can I work on this issue if its stale or not assigned to anyone?
