### ISSUE TITLE
Add Search Filters

### ISSUE THREAD

**Issue by dhruv-1001** [DSC-JSS-NOIDA/Plasma-Donor-App#117]
View donor/patient shows all the data there is on the database.
Create search filters for Blood Group and Location so that the users can see the data that they have applied the filters for.

**Comment by Khushi-24** [comment]
@dhruv-1001 Can I work on this?

**Comment by dhruv-1001** [comment]
@Khushi-24 You can start working on it.

**Comment by sitamadex11** [comment]
may I work on this issue?
@Khushi-24

**Comment by Khushi-24** [comment]
@sitamadex11 I am not working on it. You can ask the admin and then can start working.

**Comment by sitamadex11** [comment]
Okkk thankyou verymuch @Khushi-24.
@dhruv-1001 sir may I work on this issue?

**Comment by sitamadex11** [comment]
@dheerajkotwani sir, may I work on this issue?

**Comment by subhangi2731** [comment]
@dhruv-1001 @dheerajkotwani please assign me this issue I want to work
