### ISSUE TITLE
Adding Floating Action Button(2).

### ISSUE THREAD

**Issue by naman5665** [DSC-JSS-NOIDA/Plasma-Donor-App#118]
**Adding Floating Action Button For The Addition Of Plasma Donar And Patient**

Can I add a Floating Action Button on the home screen of the app.
By tapping this button and opting the desire option , user can navigate to the Add Donar or Add Patient Screen.

**Comment by dhruv-1001** [comment]
@naman5665 aren't you assigned to #96 ? It's the same issue.

**Comment by naman5665** [comment]
Hey @dhruv-1001 Yes it is same but actually there was some problem in the tree of issue96 which I could not be able to solve.Thats why I created a new issue !!!

**Comment by dhruv-1001** [comment]
Okay, I've closed the issue #96

**Comment by naman5665** [comment]
Hey @dhruv-1001 thanks for assinging the issue
