### ISSUE TITLE
Remove Deprecated class from Splash Screen

### ISSUE THREAD

**Issue by plazzy99** [DSC-JSS-NOIDA/Plasma-Donor-App#13]
**Describe the bug**
Handler class used in the splash screen is deprecated.

**To Reproduce**
1. Go to /plasmadonor/Activity/SplashActivity.kt
2. Click on SplashActivity.kt
3. Scroll down to deprecated Handler Function
4. You will see the Handler function strike-through

**Expected behavior**
Splash stays in view for the given time.

**Comment by h4rz** [comment]
Hey @plazzy99, assign this issue to me. I would be doing this as part of hacktoberfest, so I would raise a PR on or after 1st October 2020.

**Comment by plazzy99** [comment]
> Hey @plazzy99, assign this issue to me. I would be doing this as part of hacktoberfest, so I would raise a PR on or after 1st October 2020.

Hi, @h4rz !!! We're glad that you want to contribute to this project but we would advise that start contributing from 1st October so as to make it count under Hacktoberfest 2020. See you then! Keep Learning :octocat:

**Comment by plazzy99** [comment]
@h4rz till the time you can fork the project and understand the currently implemented project.

**Comment by h4rz** [comment]
@plazzy99, I have fixed this issue. Please check PR #25.
