### ISSUE TITLE
Change Splash Screen Stay time to 2.5 seconds

### ISSUE THREAD

**Issue by plazzy99** [DSC-JSS-NOIDA/Plasma-Donor-App#14]
**Is your feature request related to a problem? Please describe.**
Currently, splash screen time is too much and the user needs to wait for long.

**Describe the solution you'd like**
You can reduce the splash screen stay time to 2.5 seconds.

**Comment by varunvjha** [comment]
Please assign this issue to me.

**Comment by plazzy99** [comment]
> Please assign this issue to me.

Hi, @varunvjha !!! We're glad that you want to contribute to this project but we would advise that start contributing from 1st October so as to make it count under Hacktoberfest 2020. See you then! Keep Learning :octocat:

**Comment by varunvjha** [comment]
Okay. thanks!!

**Comment by varunvjha** [comment]
I have already submitted the PR. Please merge this @plazzy99
