### ISSUE TITLE
Prevent user from entering multiple line in input fields

### ISSUE THREAD

**Issue by dheerajkotwani** [DSC-JSS-NOIDA/Plasma-Donor-App#16]
**Describe the bug** The user can Enter Multiple lines in Input Fields in the App.

**To Reproduce**
1. Go to Any input feild.
2. Try entering multiple line input

**Expected behavior** The user should not be able to enter multiple lines in input fields.

**Screenshots**
![multi_line_input](https://user-images.githubusercontent.com/44086235/94721721-e9965d00-0373-11eb-9695-bf564491b25d.jpeg)

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open to all (Fix in all input fields)

**Comment by arpitagarwal1301** [comment]
Would like to work on it please assign it to me .

**Comment by seth0027** [comment]
Hey can I
 fix this ?

**Comment by plazzy99** [comment]
@arpitagarwal1301  assigned this issue to you.
Hope you have read the contribution guidelines

Happy Coding🥳

**Comment by plazzy99** [comment]
> Hey can I
> fix this ?

issue are assigned on a first-come basis, you can assign another issue.

**Comment by arpitagarwal1301** [comment]
@plazzy99 Issue fixed . Please check https://github.com/DSC-JSS-NOIDA/Plasma-Donor-App/pull/31

**Comment by plazzy99** [comment]
@arpitagarwal1301 make changes suggested else your issue will be assigned to someone else.

**Comment by arpitagarwal1301** [comment]
@plazzy99 Updated please check .

**Comment by fajarazay** [comment]
is it done? Would like to work on it please assign it to me now?
