### ISSUE TITLE
Make input fields to take specific input types

### ISSUE THREAD

**Issue by dheerajkotwani** [DSC-JSS-NOIDA/Plasma-Donor-App#17]
**Describe the bug**
Fields are accepting all type of values.

**To Reproduce**
1. Go to Input Fields
2. Try entering text in phone number or weight fields
3. See error

**Expected behavior**
These fields should only take specific type of input

**Screenshots**

<img src="https://user-images.githubusercontent.com/44086235/94722324-c6b87880-0374-11eb-8a57-3542af30f604.jpeg" height='500'/> <img src="https://user-images.githubusercontent.com/44086235/94722291-b99b8980-0374-11eb-91eb-851ab328773a.jpeg" height='500'/>

**Smartphone (please complete the following information):**

|               | |
|---------------|-|
|Device         | Redmi Note 4 |
|Android Version| Nougat 7.0  |

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:  Open to all

**Comment by h4rz** [comment]
@dheerajkotwani, I would like to work on it. Do mention which field needs to be of the particular data type.

**Comment by plazzy99** [comment]
@h4rz you can start working on this issue 👍🏻

**Comment by h4rz** [comment]
@plazzy99, there is already a pr mentioning this issue. #30

**Comment by plazzy99** [comment]
> @plazzy99, there is already a pr mentioning this issue. #30

np, you can raise your pr bcoz this issue is assigned to you and only assigned individual pr are considered.

**Comment by h4rz** [comment]
@plazzy99, I have fixed it. Do check the PR #51.
