### ISSUE TITLE
Implement Spinner for gender, Blood Group and similar fields

### ISSUE THREAD

**Issue by dheerajkotwani** [DSC-JSS-NOIDA/Plasma-Donor-App#18]
**Is your feature request related to a problem? Please describe.**
Currently user can enter anything in gender and blood groups sections. Use spinner to restrict to particular values.

**Describe the solution you'd like**
Implement Spinner so users are bound to particular values in case of Gender, blood group or similar fields.

<img src="https://user-images.githubusercontent.com/44086235/94723200-02077700-0376-11eb-8a87-b1dabe33d0a3.jpeg" height='500'/>

**Comment by h4rz** [comment]
@dheerajkotwani, assign this issue to me and do provide the values which need to be used in the spinner

**Comment by plazzy99** [comment]
@h4rz you can start working on this issue 👍🏻

**Comment by h4rz** [comment]
@plazzy99, to be on the same page, I will be using the below values for the spinner which will be displayed.

- **Gender**
   - Female
   - Male
   - Other

- **Blood Group**
    - A+ 
    - A- 
    - B+ 
    - B-
    - 0+
    - 0-
    - AB+
    - AB-

**Comment by h4rz** [comment]
@plazzy99, I have fixed it. Do check the PR #51.

**Comment by SwapnilSRedekar** [comment]
https://github.com/DSC-JSS-NOIDA/Plasma-Donor-App/pull/52 @plazzy99 Here's is my PR, please review the PR

**Comment by dheerajkotwani** [comment]
@SwapnilSRedekar the issue was already assigned to @h4rz
