### ISSUE TITLE
Add Loading Dialog in Login/Signup page

### ISSUE THREAD

**Issue by dheerajkotwani** [DSC-JSS-NOIDA/Plasma-Donor-App#19]
**Is your feature request related to a problem? Please describe.**
After clicking on Login/Signup button there is a delay in loading next page that should be covered with a Loading Dialog.

**Describe the solution you'd like**
After clicking the Login/Signup Button there should be a Loading Dialog which should be display while verifying user and before moving to the next screen.

![login1](https://user-images.githubusercontent.com/44086235/94724512-0765c100-0378-11eb-8996-e382afb2e06f.gif) ![login2](https://user-images.githubusercontent.com/44086235/94724520-0896ee00-0378-11eb-9927-2f2bbcac7584.gif)

**Comment by pepoflex** [comment]
Please assign me this project, I would love to work on it.

**Comment by dheerajkotwani** [comment]
@pepoflex you can start working on it. Hope you have gone through the contribution guidelines.

Happy Learning🥳

**Comment by plazzy99** [comment]
@pepoflex raise your pull request else this issue will be assigned to someone else.

**Comment by nuhkoca** [comment]
I can take this :)

**Comment by nuhkoca** [comment]
@plazzy99 last 2 days, give it to me :)
