### ISSUE TITLE
Add Circular Progress bar while loading Patients and Donor List

### ISSUE THREAD

**Issue by dheerajkotwani** [DSC-JSS-NOIDA/Plasma-Donor-App#21]
**Is your feature request related to a problem? Please describe.**
Patients and Donors list page looks empty while loading the list data.

**Describe the solution you'd like**
Add a circular progress bar which should be displayed at the center of page while loading the data for Patients and Donors list.

![progress_loader](https://user-images.githubusercontent.com/44086235/94725818-fa49d180-0379-11eb-826b-7020f8bcaf56.gif)

**Comment by erwinkaaa** [comment]
I have submitted the PR to this issue. Please review!

**Comment by erwinkaaa** [comment]
Hey @plazzy99 can you add label hacktoberfest-accepted to this PR please?
