### ISSUE TITLE
Change margin to 16dp from the broder of screen.

### ISSUE THREAD

**Issue by dheerajkotwani** [DSC-JSS-NOIDA/Plasma-Donor-App#22]
**Is your feature request related to a problem? Please describe.**
Margin for the screens are very large.

**Describe the solution you'd like**
Make the margin to 16dp from the borders for the User Details Input page.

<img src="https://user-images.githubusercontent.com/44086235/94726577-0e420300-037b-11eb-8cfa-22128b8ad988.jpeg" height='500'/>

**Comment by aadityamp01** [comment]
I would like to work on this issue, can you please assign it to me.

**Comment by plazzy99** [comment]
@aadityamp01 assigned this issue to you.
Hope you have gone through the contribution guidelines.

Happy Learning🥳
