### ISSUE TITLE
App logo instead of white screen on app start 

### ISSUE THREAD

**Issue by arpitagarwal1301** [DSC-JSS-NOIDA/Plasma-Donor-App#32]
**Is your feature request related to a problem? Please describe.**
On opening the app , user see a blank screen for some duration . This happens because untill first activity is not started , app shows system default theme which is white. 

**Describe the solution you'd like**
We can show an app logo or something like that . 

**Additional context**
https://medium.com/@shishirthedev/the-right-way-to-implement-a-splash-screen-in-android-acae0e52949a

**Comment by dheerajkotwani** [comment]
@arpitagarwal1301 you can use some icon related to blood drop

**Comment by plazzy99** [comment]
@SanushRadalage do suggest changes in your pr 

From next time,
assign the issue before raising a pull request

**Comment by arpitagarwal1301** [comment]
@plazzy99 @dheerajkotwani The above implementation is wrong there still will be a white screen before splash screen layout is loaded . We can prevent that also . Please assign it to me for the fix.
