### ISSUE TITLE
User is able to submit empty fields when filling the form.

### ISSUE THREAD

**Issue by nakul-19** [DSC-JSS-NOIDA/Plasma-Donor-App#40]
**Describe the bug**
User can submit the details even when some of the required fields are still blank.

**To Reproduce**
1. Go to Add Donor.
2. Don't fill any details in the form.
3. Click on Submit button.
4. Go to View Donor, there you could find empty donor records.

**Expected behavior**
User should not be able to submit until all the input fields are filled successfully.

**Screenshots**
![Screenshot_2020-10-02-15-11-36-640_project dscjss plasmadonor](https://user-images.githubusercontent.com/57036954/94913102-4dc93600-04c6-11eb-86f6-bfb6fc59c547.jpg)

![Screenshot_2020-10-02-15-11-51-965_project dscjss plasmadonor](https://user-images.githubusercontent.com/57036954/94913118-53268080-04c6-11eb-967e-01dba6bf8816.jpg)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by dheerajkotwani** [comment]
@nakul-19 instead of giving a toast message you can add errors to the particular fields
