### ISSUE TITLE
Setup Github Actions to ensure that new features won't break anything in the codebase

### ISSUE THREAD

**Issue by nuhkoca** [DSC-JSS-NOIDA/Plasma-Donor-App#50]
**Is your feature request related to a problem? Please describe.**
Now we might probably merge Pull Requests without test whether it works as expected and don't break anything in the current codebase. Instead of a manual check, we can automate this flow. If a new PR passes all steps, then it means to be merged.

**Describe the solution you'd like**
To set up, a Github Actions CI

**Describe alternatives you've considered**
No alternative to a CI pipeline

**Additional context**

**Comment by plazzy99** [comment]
@nuhkoca you have been assigned this issue.
You can start working on it.

Hope you have gone through the contribution guidelines.

Happy Contributing.🥳

**Comment by nuhkoca** [comment]
@plazzy99 thanks I will create an appropriate PR!
