### ISSUE TITLE
Add search tags for donor/patient list

### ISSUE THREAD

**Issue by dhruv-1001** [DSC-JSS-NOIDA/Plasma-Donor-App#56]
**Is your feature request related to a problem? Please describe.**
On opening view donors/patients the application shows all the data there is in the Firestore and a lot of which might not be useful to the user.

**Describe the solution you'd like**
Add search tags in  view donors/patients so that the user can search for a specific blood type or location.

**Comment by thearavind** [comment]
Hi @dhruv-1001 I would like to work on this issue

**Comment by dhruv-1001** [comment]
@thearavind, are you working on this issue?

**Comment by thearavind** [comment]
@dhruv-1001 Yes I will raise a PR today or tomorrow
