### ISSUE TITLE
"Profile" does not show some user information

### ISSUE THREAD

**Issue by dhruv-1001** [DSC-JSS-NOIDA/Plasma-Donor-App#59]
**Describe the bug**
On editing the profile no changes are shown.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Profile
2. Click on edit icon (Top right)
3. Input details
4. Click on save
5. See error

**Expected behaviour**
Profile should show the updated information

**Screenshots**
| Edit Profile      | Profile       |
| -------------- | -------------- |
| ![Screenshot_1602279128](https://user-images.githubusercontent.com/55213645/95634512-b5bfe380-0aa7-11eb-8324-2a05773f4fdc.png) | ![Screenshot_1602279134](https://user-images.githubusercontent.com/55213645/95634533-c4a69600-0aa7-11eb-8e09-1641d8ca04a9.png) |

**Smartphone (please complete the following information):**

|               | |
|---------------|-|
|Device         | Pixel 3a XL |
|Android Version| Oreo 8.0 |

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by EANimesha** [comment]
Can I try to fix this issue?

**Comment by plazzy99** [comment]
> Can I try to fix this issue?

yes you can start working on this issue 

Hope you have gone to through the ```contribution.md``` to make the correct pull request

Happy Coding 🥳🥳

**Comment by lingarajsankaravelu** [comment]
@EANimesha and @plazzy99 . I was working on issue #69, which was related to this issue in one way or another, So I have fixed this without knowing there was a separate issue opened.
