### ISSUE TITLE
User can't check if his password is correctly typed or not.

### ISSUE THREAD

**Issue by nakul-19** [DSC-JSS-NOIDA/Plasma-Donor-App#61]
**Describe the bug**
User can't check if his password is correctly typed or not.

**To Reproduce**
1. Go to Login/Signup Screen
2. Type something in password. 
3. You cannot see what you just entered.

**Expected behavior**
Add password visibility eye for respective fields.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by ardlank** [comment]
@nakul-19 can I work on this?

**Comment by ardlank** [comment]
PR: https://github.com/DSC-JSS-NOIDA/Plasma-Donor-App/pull/67
