### ISSUE TITLE
Add loading while login/signup.

### ISSUE THREAD

**Issue by nakul-19** [DSC-JSS-NOIDA/Plasma-Donor-App#62]
**Describe the bug**
Nothing happens when sign up or login button is clicked until the toast.

**To Reproduce**
1. Go to Login/Signup.
2. Click on Log in/Sign up button.
3. See the problem.

**Expected behavior**
Loading should be shown while logging in or signing up.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by EANimesha** [comment]
I like to work in this issue.Assign me
