### ISSUE TITLE
Not all input field errors are shown while signing up.

### ISSUE THREAD

**Issue by nakul-19** [DSC-JSS-NOIDA/Plasma-Donor-App#64]
**Describe the bug**
Not all input field errors are shown while signing up.

**To Reproduce**
1. Go to Sign up screen.
2. Click on Sign up without entering anything.
3. Input field error is shown only for Email while all the fields are empty.

**Expected behavior**
Input field errors should be shown for all faulty fields. 

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by ardlank** [comment]
@nakul-19 can I work on this?

**Comment by ardlank** [comment]
PR: https://github.com/DSC-JSS-NOIDA/Plasma-Donor-App/pull/68
