### ISSUE TITLE
Edit Profile accepting wrong data

### ISSUE THREAD

**Issue by dhruv-1001** [DSC-JSS-NOIDA/Plasma-Donor-App#66]
**Describe the bug**
Edit profile fragment accepts any type of user input in input fields

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Profile
2. Click on Edit Profile icon (Top Right)
3. Input any data

**Expected behaviour**
Blood Group and Gender should accept selected data which can be implemented using spinners
Age and Mobile should only accept numbers.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by Kardelio** [comment]
Hey there @dhruv-1001 
I have had a brief look at this and would be really interested in getting involved and trying to tackle this issue.
Would that be ok?

Also if it is ok, my next question is do you have test user accounts for development or should i just create a test account and use that?

**Comment by Kardelio** [comment]
PR: #71
