### ISSUE TITLE
Edit Profile not showing the saved data from the servers.

### ISSUE THREAD

**Issue by dheerajkotwani** [DSC-JSS-NOIDA/Plasma-Donor-App#69]
**Describe the bug**
Edit Profile not showing the saved data from the servers.

**To Reproduce**
1. Go to Profile Section.
2. Click on Edit Profile
4. See bug

**Expected behavior**
While opening the edit profile screen the data is not showing that is saved on the server.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open to all

**Comment by lingarajsankaravelu** [comment]
I like to take this up
