### ISSUE TITLE
UI enhancement.

### ISSUE THREAD

**Issue by dheerajkotwani** [DSC-JSS-NOIDA/Plasma-Donor-App#70]
**Is your feature request related to a problem? Please describe.**
The UI for the App is very basic and need a good UI for the Application.

**Describe the solution you'd like**
Create Figma File of good and modern UI following the material design guidelines for the App.

- Open to All

**Comment by gauravgeek23** [comment]
@dheerajkotwani I would like to create the Figma UI for the app.

**Comment by dheerajkotwani** [comment]
@gauravgeek23 you can start working on it.
