### ISSUE TITLE
Introduce FAQ Screen

### ISSUE THREAD

**Issue by nuhkoca** [DSC-JSS-NOIDA/Plasma-Donor-App#73]
**Additional context**
Implementing FAQ screens with content. How can I do that? Is there a prepared text?

I'd like to work on this feature.

**Comment by jcasteele** [comment]
I'd be interested in working on a FAQ screen for the app. The main page mentions an FAQ regarding details about plasma; would this be the implementation of that (I'm assuming with information about plasma and plasma donation) or would this be supplemental information to go with an existing FAQ?

**Comment by nuhkoca** [comment]
Let's wait for a comment from one of the maintainers. Unfortunately, I'll take this feature to complete. You can check missing parts of the project in README and create a feature proposal, though.

**Comment by Jeewantha95** [comment]
Hi, I would like to work on this feature. Please assign it to me.

**Comment by nuhkoca** [comment]
Sorry, I opened this issue to take on me.

**Comment by dheerajkotwani** [comment]
@nuhkoca there's already a FAQ page added to the app you can search some content related to app that can be useful for the users and add to it.

**Comment by nuhkoca** [comment]
@dheerajkotwani yes, I will fix the data fetch method for this screen how I did in the Donor and Patient screens. In the meantime, how can I add extra FAQs to the Firebase collection?

**Comment by nuhkoca** [comment]
cc @plazzy99

**Comment by dheerajkotwani** [comment]
> 
> 
> @dheerajkotwani yes, I will fix the data fetch method for this screen like how I did in the Donor and Patient screens. In the meantime, how can I add extra FAQs to the Firebase collection?

provide your email so I can add you to it till you are working on this

**Comment by nuhkoca** [comment]
@dheerajkotwani it is nuhkocatest@gmail.com

**Comment by nuhkoca** [comment]
@dheerajkotwani last 2 days, pls speed it up :)

**Comment by dheerajkotwani** [comment]
@nuhkoca added you to firebase console
