### ISSUE TITLE
Sign in with Google Bug(not Working)

### ISSUE THREAD

**Issue by sumit619sharma** [DSC-JSS-NOIDA/Plasma-Donor-App#81]
**Describe the** **bug**
Sign in with Google is not Working getting error on Sign in

**To Reproduce**

    1. Go to Login screen
    2. Click on 'Sign in with Google'
    4. Add the 'email ID'
    3. See error "Login Failed 10"

**Expected behavior**
Should be able to Sign in with Google
Should follow UI guideline for implementing Sign in with Google button

**Screenshots**
![Screenshot_20201227-141407_Google_Play_services 1](https://user-images.githubusercontent.com/72352873/103167056-bdf10a80-47dc-11eb-878d-cc797efcdb9c.jpg)
![Screenshot_20201227-135054_Plasma_Donor_App 1](https://user-images.githubusercontent.com/72352873/103167064-ce08ea00-47dc-11eb-9f3a-61fbe233a38e.jpg)

**Smartphone (please complete the following information):**

|               | |
|---------------|-|
|Device         |Samsung J8| |
|Android Version |Android 10| |

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by plazzy99** [comment]
this is because your sha1 key is not added to the project.

**Comment by sumit619sharma** [comment]
Where i can get this sha 1 key

**Comment by plazzy99** [comment]
> Where i can get this sha 1 key

Here is the StackOverflow answer to get your sha1 key
https://stackoverflow.com/a/34223470/12203379

send me on a LinkedIn or Twitter dm 
Refer to my profile for links.

**Comment by sumit619sharma** [comment]
I m not able to connect my project with Firebase it show's  Gradle build issue. help me I stuck there from last week.

**Comment by plazzy99** [comment]
> I m not able to connect my project with Firebase it show's Gradle build issue. help me I stuck there from last week.

Are you working on the same or different project?

**Comment by sumit619sharma** [comment]
same project, you assigned me add fb Login issue sir.

**Comment by sumit619sharma** [comment]
same project. Sir you assigned me add fb Login issue.

**Comment by rohitsigar** [comment]
To set up Google Sign-In for your Android apps, you need to add the SHA1 fingerprint for each app in your Project settings and also enable the google option in sign-in provider in the firebase console.

**Comment by sudhansukinng** [comment]
Hello, @sumit619sharma please assign me this issue.  I would like to work on this issue.

**Comment by Kaustubh-Umbarkar** [comment]
@dheerajkotwani can you assign me this issue ,I can help.

**Comment by sudhansukinng** [comment]
@dheerajkotwani, thank you for assigning.

**Comment by BHAVESH24042000** [comment]
can I work on this issue, I am not a participant of GSSOC but willing to work on firebase related issues.

**Comment by Shaswat-2203** [comment]
Hey can I work on this issue for GSSOC21?

**Comment by snehagarg-bit** [comment]
@dheerajkotwani I try to run this app but its not running due to google sign in error can I work on this issue.
