### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [DSC-JSS-NOIDA/Plasma-Donor-App#83]
Hey!
I would like to add the following in the contributing.md -

1. Difference between GIT and GITHUB
2. How to clone,fork repository
3. How to create a branch and then use git push to push to repo
4. Create a PR
5.Squash commits in a single issue into one
6. Updating the forked and local repo as the updations are made in the upstream

**Comment by raghav-dalmia** [comment]
@PragatiVerma18 have a look at the relevance of the issue.
