### ISSUE TITLE
Profile edit page - Unclear edit fields

### ISSUE THREAD

**Issue by codeDamon** [DSC-JSS-NOIDA/Plasma-Donor-App#84]
**Describe the bug**
* In the Edit Profile Page, few of the fields are shown by default by 'Not Provided'
* There is not even any heading to these fields
* User has to first clear the EditText in order to view the hint.

**To Reproduce**
1. Open Profile from Drawer.
2. Click on edit icon present on the top right corner 
3. See the edit texts with 'Not Provided'

**Expected behavior**
* It should be clear what data needs to be entered to the user
* For achieving this there can be two ways :
    1. If fields are 'Not Provided', don't display them. By this way hint will be displayed.
    2. Other way, add headings to all the edit texts.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Screenshots**
![ss](https://user-images.githubusercontent.com/59572531/111042390-26a66580-8463-11eb-84a7-87a273f9e17c.jpg)

**Comment by raghav-dalmia** [comment]
@codeDamon go ahead.

**Comment by AnubhavPabby** [comment]
@dheerajkotwani can I work on this issue?
