### ISSUE TITLE
No Lables in Top app bar 

### ISSUE THREAD

**Issue by codeDamon** [DSC-JSS-NOIDA/Plasma-Donor-App#85]
**Describe the bug**
* In any page, there are no Lables.
* It only shows the name of the app

**Expected behavior**
* Every page should have specific lables to distinguish them.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by anshul3pathi** [comment]
Hello, I'd like to work on this issue.
Also, can you tell what should be the specific title of each page, like should it correspond to the names of pages in the nav drawer?
