### ISSUE TITLE
[Optional Fix] Expanded FAQ has downward arrow

### ISSUE THREAD

**Issue by codeDamon** [DSC-JSS-NOIDA/Plasma-Donor-App#86]
**Describe the bug**
* When user expand a Question in FAQ, the arrow still points down

**To Reproduce**
1. Go to FAQ page
2. Click on any question
3. See error - arrow direction not changed

**Expected behavior**

Ideally arrow direction should point upwards when expanded.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Screenshots**

![ss](https://user-images.githubusercontent.com/59572531/111042830-48a0e780-8465-11eb-9221-acb6bb259613.jpg)

**Comment by dheerajkotwani** [comment]
@codeDamon you can make the icon changing to upward or downward points according to its expanded or not
