### ISSUE TITLE
[Feature Request] - Dark Theme Support

### ISSUE THREAD

**Issue by codeDamon** [DSC-JSS-NOIDA/Plasma-Donor-App#87]
**Is feature request related to a problem?**
I believe dark mode is the need for this hour. 
Every app and websites are releasing dark mode feature. 
There should be dark mode for this app too.

**Describe the solution**
Implementing day/night support.

I can work on this, if this issue is appropiate.

**Comment by dheerajkotwani** [comment]
We will be adding the UI for the app you can accordingly design the dark theme UI for it.
