### ISSUE TITLE
Add a logo to the app

### ISSUE THREAD

**Issue by anushka530** [DSC-JSS-NOIDA/Plasma-Donor-App#89]
I will design a logo for app and add it as launcher icon

**Comment by snehagarg-bit** [comment]
Along with logo we can also add the app launcher icon in Splash Screeen.

**Comment by dheerajkotwani** [comment]
@snehagarg-bit you can design the icon for the app, we can use if we liked,

**Comment by snehagarg-bit** [comment]
@dheerajkotwani ohky I will design the icon from this app and what about adding the launcher icon in splash screen?
