### ISSUE TITLE
Adding Floating Action Button

### ISSUE THREAD

**Issue by naman5665** [DSC-JSS-NOIDA/Plasma-Donor-App#96]
**Adding Floating Action Button For The Addition Of Plasma Donar And Patient**
Can I add a Floating Action Button on the home screen of the app.
By tapping this button and opting the desire option , user can navigate to the Add Donar or Add Patient Screen.

**Comment by dheerajkotwani** [comment]
@naman5665 you can start working on this

**Comment by naman5665** [comment]
Thanks @dheerajkotwani

**Comment by naman5665** [comment]
Hey @dheerajkotwani I think I have solved the conflicts.Kindly review.
