### ISSUE TITLE
NEW  ICON FOR THE ANDROID APP

### ISSUE THREAD

**Issue by palsumit99** [DSC-JSS-NOIDA/Plasma-Donor-App#97]
I would like to design a new icon for the application.
Please assign me the issue 
[gssoc21]

**Comment by palsumit99** [comment]
Admin i want to solve this issue.
Please assign me

**Comment by dheerajkotwani** [comment]
@palsumit99 you can design an icon for the app, we can use it if we liked,

**Comment by pallavidhere23** [comment]
@dheerajkotwani ,Can I work on this Issue?
