### ISSUE TITLE
ADDING A NEW MAP API FOR FINDING THE PLASMA DONOR NEAR YOU

### ISSUE THREAD

**Issue by palsumit99** [DSC-JSS-NOIDA/Plasma-Donor-App#98]
Instead of adding location.
The app will detect the gps location of the plasma donor.
When someone needs plasma he/she needs to search for the particular blood group.
He/she will get location of the nearest plasma donors pin pointed.
I want to add this feature please assign me.

**Comment by dheerajkotwani** [comment]
@palsumit99 You can use Google Maps API for implementing this and can display some custom markers on the map showing the nearby Plasma Donors.

**Comment by subhangi2731** [comment]
@dheerajkotwani please assign me this issue I see the pr has not been made I want to work
