### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by dheerajkotwani** [DSC-JSS-NOIDA/Plasma-Donor-App#99]
**Is your feature request related to a problem? Please describe.**
The current UI is very basic. Participants can start picking some screens and start improving the UI for them.

**Describe the solution you'd like**
The new UI for the app can be found at https://www.figma.com/file/XNhCtffUPBLx5SrbUH9Fmf/Plasma-Doner-App?node-id=0%3A1

**Additional context**
Comment the screen you will be working on and create issue for the same so you can start working on it.

**Comment by sitamadex11** [comment]
I want to work on UI enhancement

**Comment by dheerajkotwani** [comment]
@sitamadex11 which screen will you be working on?

**Comment by sitamadex11** [comment]
@dheerajkotwani , sir I want to work on login page.

**Comment by dheerajkotwani** [comment]
@sitamadex11 you can start working on login page ui

**Comment by sitamadex11** [comment]
@dheerajkotwani ok thankyou

**Comment by sitamadex11** [comment]
sir, may I have to create an issue for that?

**Comment by dheerajkotwani** [comment]
@sitamadex11 you can create a separate issue for that screen

**Comment by sitamadex11** [comment]
@dheerajkotwani sir I have created a new issue

**Comment by gargijs** [comment]
> > I want to work on UI of Profile page.
> 
> You can create an Issue for that page.

I have already created an issue for this. issue #131

**Comment by ritmojs** [comment]
I want to work on Do you want to donate Plasma? UI Please assign this to me.

**Comment by Ayushi7456** [comment]
I would like to work on this as GSSOC participant. Is someone assigned to this or i can create new issue?
